/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author User
 */
public class EventManage extends javax.swing.JFrame {

    /**
     * Creates new form EventManage
     */
    public EventManage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        new_event = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        new_venue = new javax.swing.JTextField();
        new_date = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        new_about = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        new_ticket_details = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        addEvent = new javax.swing.JButton();
        clear_bttn1 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        select_event = new java.awt.Choice();
        jSeparator1 = new javax.swing.JSeparator();
        select_bttn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        updateVenue = new javax.swing.JTextField();
        updateDate = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        updateAbout = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        updateTicket = new javax.swing.JTable();
        Update_bttn = new javax.swing.JButton();
        clear_bttn2 = new javax.swing.JButton();
        delete_event = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 42)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText(" Event Management ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 430, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 80));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Add New Event  ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calisto MT", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        new_event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_eventActionPerformed(evt);
            }
        });
        jPanel3.add(new_event, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 460, -1));

        jLabel3.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("About :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 70, 30));

        jLabel4.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Event :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 70, 30));

        new_venue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_venueActionPerformed(evt);
            }
        });
        jPanel3.add(new_venue, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 230, -1));
        jPanel3.add(new_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 340, -1));

        jLabel8.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Date :");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 70, 30));

        new_about.setColumns(20);
        new_about.setRows(5);
        jScrollPane1.setViewportView(new_about);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 230, 80));

        new_ticket_details.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Category (Type)", "No. of seats", "Ticket price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(new_ticket_details);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 350, 80));

        jLabel9.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ticket Details :");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 130, 30));

        addEvent.setBackground(new java.awt.Color(204, 204, 204));
        addEvent.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        addEvent.setText("Add ");
        addEvent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addEvent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEventActionPerformed(evt);
            }
        });
        jPanel3.add(addEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 70, 30));

        clear_bttn1.setBackground(new java.awt.Color(204, 204, 204));
        clear_bttn1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        clear_bttn1.setText("Clear");
        clear_bttn1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear_bttn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(clear_bttn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 60, 30));

        back.setBackground(new java.awt.Color(204, 204, 204));
        back.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        back.setText("Back");
        back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel3.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 70, 30));

        jLabel7.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Venue :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 70, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 900, 270));

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Update Event ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calisto MT", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ticket Details  :");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 140, 30));

        jLabel10.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Venue :");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 70, 30));

        jLabel11.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Date :");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 70, 30));

        jLabel12.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Existing Event :");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 140, 30));
        jPanel4.add(select_event, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 470, 40));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 900, 10));

        select_bttn.setBackground(new java.awt.Color(204, 204, 204));
        select_bttn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        select_bttn.setText("Select");
        select_bttn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        select_bttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(select_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 70, 30));

        jLabel13.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("About :");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 70, 30));

        updateVenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateVenueActionPerformed(evt);
            }
        });
        jPanel4.add(updateVenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 230, -1));
        jPanel4.add(updateDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 330, -1));

        updateAbout.setColumns(20);
        updateAbout.setRows(5);
        jScrollPane3.setViewportView(updateAbout);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 230, -1));

        updateTicket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Category (type)", "No. of seats", "Ticket price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(updateTicket);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 340, 90));

        Update_bttn.setBackground(new java.awt.Color(204, 204, 204));
        Update_bttn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Update_bttn.setText("Update");
        Update_bttn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Update_bttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(Update_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 70, 30));

        clear_bttn2.setBackground(new java.awt.Color(204, 204, 204));
        clear_bttn2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        clear_bttn2.setText("Clear");
        clear_bttn2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear_bttn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear_bttn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_bttn2ActionPerformed(evt);
            }
        });
        jPanel4.add(clear_bttn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 70, 30));

        delete_event.setBackground(new java.awt.Color(204, 204, 204));
        delete_event.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        delete_event.setText("Delete Event");
        delete_event.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(delete_event, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 90, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 890, 330));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void new_eventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_eventActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_eventActionPerformed

    private void new_venueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_venueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_venueActionPerformed

    private void addEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEventActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addEventActionPerformed

    private void updateVenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateVenueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateVenueActionPerformed

    private void clear_bttn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_bttn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clear_bttn2ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        AdminProfile adminNew = new AdminProfile();
        adminNew.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventManage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Update_bttn;
    private javax.swing.JButton addEvent;
    private javax.swing.JButton back;
    private javax.swing.JButton clear_bttn1;
    private javax.swing.JButton clear_bttn2;
    private javax.swing.JButton delete_event;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea new_about;
    private javax.swing.JTextField new_date;
    private javax.swing.JTextField new_event;
    private javax.swing.JTable new_ticket_details;
    private javax.swing.JTextField new_venue;
    private javax.swing.JButton select_bttn;
    private java.awt.Choice select_event;
    private javax.swing.JTextArea updateAbout;
    private javax.swing.JTextField updateDate;
    private javax.swing.JTable updateTicket;
    private javax.swing.JTextField updateVenue;
    // End of variables declaration//GEN-END:variables
}
