/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author User
 */
public class Reserve extends javax.swing.JFrame {

    /**
     * Creates new form Reserve
     */
    public Reserve() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        event = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        seatType = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        seatcount = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        value = new javax.swing.JFormattedTextField();
        caltotal = new javax.swing.JButton();
        clear_booking = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        master = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        visa = new javax.swing.JRadioButton();
        paypal = new javax.swing.JRadioButton();
        cardnum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        expiryDate = new javax.swing.JFormattedTextField();
        paybtn = new javax.swing.JButton();
        digits = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Back_user = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Sitka Text", 1, 38)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Book Now!");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 230, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 100));

        jLabel12.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Event :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 70, -1));

        event.setEditable(false);
        event.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventActionPerformed(evt);
            }
        });
        jPanel1.add(event, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 240, -1));

        jLabel11.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Type :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        seatType.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        seatType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "a", "b", "c" }));
        seatType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatTypeActionPerformed(evt);
            }
        });
        jPanel1.add(seatType, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 90, -1));

        jLabel3.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("No. of  Tickets :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        seatcount.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        seatcount.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        jPanel1.add(seatcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 160, 80, -1));

        jLabel10.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Value :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        value.setEditable(false);
        value.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤¤#,##0.00"))));
        value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueActionPerformed(evt);
            }
        });
        jPanel1.add(value, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 110, -1));

        caltotal.setBackground(new java.awt.Color(204, 204, 204));
        caltotal.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        caltotal.setText("Total");
        caltotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        caltotal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        caltotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caltotalActionPerformed(evt);
            }
        });
        jPanel1.add(caltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 50, 30));

        clear_booking.setBackground(new java.awt.Color(204, 204, 204));
        clear_booking.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        clear_booking.setText("Clear");
        clear_booking.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear_booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_bookingActionPerformed(evt);
            }
        });
        jPanel1.add(clear_booking, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 60, 30));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Payment ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Palatino Linotype", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        master.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        master.setForeground(new java.awt.Color(255, 255, 255));
        master.setText("Master");
        master.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterActionPerformed(evt);
            }
        });
        jPanel3.add(master, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jLabel13.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Payment Type:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 130, -1));

        visa.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        visa.setForeground(new java.awt.Color(255, 255, 255));
        visa.setText("Visa");
        visa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visaActionPerformed(evt);
            }
        });
        jPanel3.add(visa, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        paypal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        paypal.setForeground(new java.awt.Color(255, 255, 255));
        paypal.setText("Paypal");
        jPanel3.add(paypal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        cardnum.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        cardnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardnumActionPerformed(evt);
            }
        });
        jPanel3.add(cardnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 270, -1));

        jLabel4.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MM/YY :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 90, 20));

        expiryDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("MM/YY"))));
        expiryDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expiryDateActionPerformed(evt);
            }
        });
        jPanel3.add(expiryDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 80, -1));

        paybtn.setBackground(new java.awt.Color(204, 204, 204));
        paybtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        paybtn.setText("Pay");
        paybtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        paybtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paybtnActionPerformed(evt);
            }
        });
        jPanel3.add(paybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 70, 30));
        jPanel3.add(digits, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 70, -1));

        jLabel5.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CVV code:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Card Number :");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        Back_user.setBackground(new java.awt.Color(204, 204, 204));
        Back_user.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Back_user.setText("Back");
        Back_user.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Back_user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_userActionPerformed(evt);
            }
        });
        jPanel3.add(Back_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 50, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 500, 200));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void eventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventActionPerformed

    private void seatTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatTypeActionPerformed

    private void valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueActionPerformed

    private void caltotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caltotalActionPerformed
        // TODO add your handling code here:
        String seat = seatType.getSelectedItem().toString();
        int count = Integer.parseInt(seatcount.getValue().toString());
        int ttl = 0;

        switch(seat){
            case "a":
            ttl = count*5000;
            break;

            case "b":
            ttl = count*2000;
            break;

            case "c":
            ttl = count*1000;
            break;
        }
        value.setText(String.valueOf(ttl));

    }//GEN-LAST:event_caltotalActionPerformed

    private void clear_bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_bookingActionPerformed
        // TODO add your handling code here:
        value.setText("");
        
    }//GEN-LAST:event_clear_bookingActionPerformed

    private void masterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masterActionPerformed

    private void visaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visaActionPerformed

    private void cardnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardnumActionPerformed

    private void expiryDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expiryDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expiryDateActionPerformed

    private void paybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paybtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paybtnActionPerformed

    private void Back_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_userActionPerformed
        // TODO add your handling code here:
        UserProfile userRes = new UserProfile();
        userRes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Back_userActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reserve().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_user;
    private javax.swing.JButton caltotal;
    private javax.swing.JTextField cardnum;
    private javax.swing.JButton clear_booking;
    private javax.swing.JTextField digits;
    private javax.swing.JTextField event;
    private javax.swing.JFormattedTextField expiryDate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton master;
    private javax.swing.JButton paybtn;
    private javax.swing.JRadioButton paypal;
    private javax.swing.JComboBox<String> seatType;
    private javax.swing.JSpinner seatcount;
    private javax.swing.JFormattedTextField value;
    private javax.swing.JRadioButton visa;
    // End of variables declaration//GEN-END:variables
}
