/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;
import CODE.DbConnect;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

public class UpdateUserInfo extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    public int userID;
    
    public UpdateUserInfo() throws SQLException {
        initComponents();
        conn= DbConnect.connect();
        showDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        backUser_bttn = new javax.swing.JButton();
        clearbttn = new javax.swing.JButton();
        updateinfobtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        oldname = new javax.swing.JTextField();
        newname = new javax.swing.JTextField();
        newEmail = new javax.swing.JTextField();
        newPassword = new javax.swing.JPasswordField();
        oldPassword = new javax.swing.JPasswordField();
        newContact = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        details_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText(" Profile Details ");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 102, 102)));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 90));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Details Update ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backUser_bttn.setBackground(new java.awt.Color(204, 204, 204));
        backUser_bttn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        backUser_bttn.setText("Back");
        backUser_bttn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backUser_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backUser_bttnActionPerformed(evt);
            }
        });
        jPanel3.add(backUser_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 60, -1));

        clearbttn.setBackground(new java.awt.Color(204, 204, 204));
        clearbttn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        clearbttn.setText("Clear");
        clearbttn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clearbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbttnActionPerformed(evt);
            }
        });
        jPanel3.add(clearbttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 60, -1));

        updateinfobtn.setBackground(new java.awt.Color(204, 204, 204));
        updateinfobtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        updateinfobtn.setText("Update");
        updateinfobtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updateinfobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateinfobtnActionPerformed(evt);
            }
        });
        jPanel3.add(updateinfobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 70, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("New Password :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, 20));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("New Contact : ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, 20));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("New Email :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, 20));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New User Name :");
        jLabel2.setToolTipText("");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 140, 20));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Old User Name :");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, 20));

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Old Password :");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, 20));

        oldname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldnameActionPerformed(evt);
            }
        });
        jPanel3.add(oldname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 300, -1));

        newname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newnameActionPerformed(evt);
            }
        });
        jPanel3.add(newname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 300, -1));

        newEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEmailActionPerformed(evt);
            }
        });
        jPanel3.add(newEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 300, -1));

        newPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPasswordActionPerformed(evt);
            }
        });
        jPanel3.add(newPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 300, -1));

        oldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldPasswordActionPerformed(evt);
            }
        });
        jPanel3.add(oldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 300, -1));

        newContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newContactActionPerformed(evt);
            }
        });
        jPanel3.add(newContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 300, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 640, 330));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        details_table.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        details_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "User name", "Email", "Contact", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        details_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                details_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(details_table);
        if (details_table.getColumnModel().getColumnCount() > 0) {
            details_table.getColumnModel().getColumn(0).setHeaderValue("User name");
            details_table.getColumnModel().getColumn(1).setHeaderValue("Email");
            details_table.getColumnModel().getColumn(2).setHeaderValue("Contact");
            details_table.getColumnModel().getColumn(3).setHeaderValue("Password");
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 630, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateinfobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateinfobtnActionPerformed
        // TODO add your handling code here:
        String oldn = oldname.getText();
        String newn = newname.getText();
        String oldp = String.valueOf(oldPassword.getPassword());
        String newp = String.valueOf(newPassword.getPassword());
        String nContact = newContact.getText();
        String nEmail = newEmail.getText();
        
        if(oldn.isEmpty()|| newn.isEmpty()||oldp.isEmpty()||newp.isEmpty()|| nContact.isEmpty()|| nEmail.isEmpty() ){
            JOptionPane.showMessageDialog(this, "Enter Details");}
        else if(newp.length() < 8||newp.equals(oldp)){
            JOptionPane.showMessageDialog(null, "Check the new Password again!");
        }
        else if(nContact.length()!= 10){
        JOptionPane.showMessageDialog(null, "Check the new conatct number again");}
        else{
            try{
                if (this.conn == null || this.conn.isClosed()) {
                // Re-establish the connection
                String jdbcUrl = "jdbc:mysql://localhost:3306/event_reservation";
                String username = "root";
                String password = "";
                this.conn = DriverManager.getConnection(jdbcUrl, username, password);
                }
                String sql = "UPDATE user SET user_name = ?, user_password = ?, mobile_number = ?, email= ? WHERE user_name=? , user_password=?";
                PreparedStatement add = conn.prepareStatement(sql);
                add.setString(1,newn);
                add.setString(2,newp);
                add.setString(3,nContact);
                add.setString(4,nEmail);
                add.setString(5,oldn);
                add.setString(6,oldp);
                add.executeUpdate();
                JOptionPane.showMessageDialog(null,"Update Sucessfully!");
                
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,"Error occurs at Update info button: "+e);
            }
        }
        

    }//GEN-LAST:event_updateinfobtnActionPerformed

    private void newnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newnameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_newnameActionPerformed

    private void newEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newEmailActionPerformed

    private void newPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPasswordActionPerformed

    private void newContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newContactActionPerformed

    private void backUser_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backUser_bttnActionPerformed
        try {
            // TODO add your handling code here:
            UserProfile userNew = new UserProfile();
            userNew.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_backUser_bttnActionPerformed

    private void clearbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbttnActionPerformed
        // TODO add your handling code here:
        oldname.setText("");
        newname.setText("");
        newPassword.setText("");
        oldPassword.setText("");
        newEmail.setText("");
        newContact.setText("");
    }//GEN-LAST:event_clearbttnActionPerformed

    private void oldnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldnameActionPerformed

    private void oldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldPasswordActionPerformed

    private void details_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_details_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)details_table.getModel();
    }//GEN-LAST:event_details_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateUserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateUserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateUserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateUserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new UpdateUserInfo().setVisible(true);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backUser_bttn;
    private javax.swing.JButton clearbttn;
    private javax.swing.JTable details_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField newContact;
    private javax.swing.JTextField newEmail;
    private javax.swing.JPasswordField newPassword;
    private javax.swing.JTextField newname;
    private javax.swing.JPasswordField oldPassword;
    private javax.swing.JTextField oldname;
    private javax.swing.JButton updateinfobtn;
    // End of variables declaration//GEN-END:variables
private void showDetails()throws SQLException {
        try {
            String sqlNew = "SELECT * where user_ID=? ";
            pst = conn.prepareStatement(sqlNew);
            pst.setInt(1, userID);
            rs = pst.executeQuery();
            while(rs.next()){
                String seat_type = rs.getString("seat_category");
                String number_of = String.valueOf(rs.getInt("NoOf_seats"));
                String eventName = rs.getString("event_Name");
                
                String tbDataNew[]= {seat_type,number_of ,eventName};
                DefaultTableModel tblModel = (DefaultTableModel)details_table.getModel();
               
                tblModel.addRow(tbDataNew);
            }
             }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null,e);
            }
    }
}

