
package GUI;

import javax.swing.JOptionPane;
import CODE.DbConnect;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

public class UpdateUserInfo extends javax.swing.JFrame {

    Connection conn = null;
    
    String user_name;
    
    
    public UpdateUserInfo(String user_name) throws SQLException {
        initComponents();
        conn= DbConnect.connect();
        showDetails(user_name);
        Reconnect();
    }

    public UpdateUserInfo() {
        try {
            initComponents();
            conn= DbConnect.connect();
            showDetails(user_name);
            Reconnect();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Error occurs at UpdateUserInfo constructor : "+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        backUser_bttn = new javax.swing.JButton();
        clearbttn = new javax.swing.JButton();
        updateinfobtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        newname = new javax.swing.JTextField();
        newEmail = new javax.swing.JTextField();
        newPassword = new javax.swing.JPasswordField();
        oldPassword = new javax.swing.JPasswordField();
        newContact = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText(" Profile Details ");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 102, 102)));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 90));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Details Update ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backUser_bttn.setBackground(new java.awt.Color(204, 204, 204));
        backUser_bttn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        backUser_bttn.setText("Back");
        backUser_bttn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backUser_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backUser_bttnActionPerformed(evt);
            }
        });
        jPanel3.add(backUser_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 60, -1));

        clearbttn.setBackground(new java.awt.Color(204, 204, 204));
        clearbttn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        clearbttn.setText("Clear");
        clearbttn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clearbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbttnActionPerformed(evt);
            }
        });
        jPanel3.add(clearbttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 60, -1));

        updateinfobtn.setBackground(new java.awt.Color(204, 204, 204));
        updateinfobtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        updateinfobtn.setText("Update");
        updateinfobtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updateinfobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateinfobtnActionPerformed(evt);
            }
        });
        jPanel3.add(updateinfobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 70, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("New Password :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, 20));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("New Contact : ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 20));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("New Email :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, 20));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New User Name :");
        jLabel2.setToolTipText("");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 140, 20));

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Old Password :");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, 20));

        newname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newnameActionPerformed(evt);
            }
        });
        jPanel3.add(newname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 300, -1));

        newEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEmailActionPerformed(evt);
            }
        });
        jPanel3.add(newEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 300, -1));

        newPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPasswordActionPerformed(evt);
            }
        });
        jPanel3.add(newPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 300, -1));

        oldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldPasswordActionPerformed(evt);
            }
        });
        jPanel3.add(oldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 300, -1));

        newContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newContactActionPerformed(evt);
            }
        });
        jPanel3.add(newContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 300, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 640, 310));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateinfobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateinfobtnActionPerformed
        // TODO add your handling code here:
        
        String newn = newname.getText();
        String oldp = String.valueOf(oldPassword.getPassword());
        String newp = String.valueOf(newPassword.getPassword());
        String nContact = newContact.getText();
        String nEmail = newEmail.getText();
        
        if(oldp.isEmpty()|| newn.isEmpty()||newp.isEmpty()|| nContact.isEmpty()|| nEmail.isEmpty() ){
            JOptionPane.showMessageDialog(this, "Enter Details");}
        else if(newp.length() < 8||newp.equals(oldp)){         
        // TODO add your handling code here:
            JOptionPane.showMessageDialog(null, "Check the new Password again!");
        }else if(checkUserName(newn)){
            JOptionPane.showMessageDialog(null, "Already Registered with this name. \n\bPlease Use different name");
        }
        else if(nContact.length()!= 10){
        JOptionPane.showMessageDialog(null, "Check the new conatct number again");}
        else{
            try{
                String sql = "UPDATE user SET user_name = ?, user_password = ?, mobile_number = ?, email= ? WHERE user_name=? , user_password=?";
                PreparedStatement add = conn.prepareStatement(sql);
                add.setString(1,newn);
                add.setString(2,newp);
                add.setString(3,nContact);
                add.setString(4,nEmail);
                add.setString(5,user_name);
                add.setString(6,oldp);
                add.executeUpdate();
                JOptionPane.showMessageDialog(null,"Update Sucessfully!");
                
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,"Error occurs at Update info button: "+e);
            }
        }
        

    }//GEN-LAST:event_updateinfobtnActionPerformed

    private void newnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newnameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_newnameActionPerformed

    private void newEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newEmailActionPerformed

    private void newPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPasswordActionPerformed

    private void newContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newContactActionPerformed

    private void backUser_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backUser_bttnActionPerformed
        try {
            // TODO add your handling code here:
            UserProfile userNew = new UserProfile(user_name);
            userNew.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_backUser_bttnActionPerformed

    private void clearbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbttnActionPerformed
        // TODO add your handling code here:
        newname.setText("");
        newPassword.setText("");
        oldPassword.setText("");
        newEmail.setText("");
        newContact.setText("");
    }//GEN-LAST:event_clearbttnActionPerformed

    private void oldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateUserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateUserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateUserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateUserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UpdateUserInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backUser_bttn;
    private javax.swing.JButton clearbttn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField newContact;
    private javax.swing.JTextField newEmail;
    private javax.swing.JPasswordField newPassword;
    private javax.swing.JTextField newname;
    private javax.swing.JPasswordField oldPassword;
    private javax.swing.JButton updateinfobtn;
    // End of variables declaration//GEN-END:variables
private void Reconnect() throws SQLException{
    if (this.conn == null || this.conn.isClosed()) {
        try {
            // Re-establish the connection
            String jdbcUrl = "jdbc:mysql://localhost:3306/event_reservation";
            String username = "root";
            String db_password = null;
            this.conn = DriverManager.getConnection(jdbcUrl, username, db_password);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Error occurs When reconnecting Database :"+e);
        }
    }
}
private boolean checkUserName(String name){
    String sql = "SELECT  user_name FROM user WHERE user_name=?";
        try{
            PreparedStatement add = conn.prepareStatement(sql);
            add.setString(1, name);
            ResultSet rst = add.executeQuery();
            return rst.next();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Error occurs at checking AdminName : "+e);
        }
        return false;
}
private void showDetails(String name)throws SQLException {
        try {
            String sql = "SELECT * FROM user where user_name=? ";
            PreparedStatement add = conn.prepareStatement(sql);
            add.setString(1,name);
            ResultSet rs = add.executeQuery();
            while(rs.next()){
                String user_old_name = rs.getString("user_name");
                String user_Password = rs.getString("user_password");
                String user_contact = rs.getString("mobile_number");
                String user_Email = rs.getString("email");
                
                String tbDataNew[]= {user_old_name,user_Email ,user_contact,user_Password};
                DefaultTableModel tblModel = (DefaultTableModel)details_table.getModel();
               
                tblModel.addRow(tbDataNew);
            }
             }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Error occurs at showing current details"+e);
            }
    }
}

