
package GUI;
import CODE.DbConnect;
import java.sql.PreparedStatement;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.SQLException;



public class UserReg extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    
    public UserReg() throws SQLException {
        initComponents();
        conn= DbConnect.connect();
        // If connection lost with DbConnect 
        Reconnect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        uName = new javax.swing.JTextField();
        eMail = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        register_bttn = new javax.swing.JButton();
        clear_bttn = new javax.swing.JButton();
        back_log_bttn = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText(" Register here! ");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 102, 102)));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 310, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 100));

        jLabel5.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("User Name :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contact Number:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));
        jPanel1.add(uName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 210, -1));
        jPanel1.add(eMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 210, -1));
        jPanel1.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 210, -1));

        register_bttn.setBackground(new java.awt.Color(204, 204, 204));
        register_bttn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        register_bttn.setText("Register");
        register_bttn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        register_bttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_bttnActionPerformed(evt);
            }
        });
        jPanel1.add(register_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 304, 60, 30));

        clear_bttn.setBackground(new java.awt.Color(204, 204, 204));
        clear_bttn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        clear_bttn.setText("Clear");
        clear_bttn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear_bttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_bttnActionPerformed(evt);
            }
        });
        jPanel1.add(clear_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 50, 30));

        back_log_bttn.setBackground(new java.awt.Color(204, 204, 204));
        back_log_bttn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        back_log_bttn.setText("Back");
        back_log_bttn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back_log_bttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_log_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_log_bttnActionPerformed(evt);
            }
        });
        jPanel1.add(back_log_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 40, 30));
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 210, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -2, 490, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void register_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_bttnActionPerformed
        // TODO add your handling code here:
        String user_name = uName.getText();
        String user_password = String.valueOf(password.getPassword());
        String user_email = eMail.getText();
        String user_number = contact.getText();
        
        if(user_name.equals("") || user_password.equals("") || user_number.equals("") || user_email.equals("")){
            JOptionPane.showMessageDialog(null, "Fill all the fields!");
        }
        else if(user_password.length() < 8){
            JOptionPane.showMessageDialog(null, "The password should contain at least 8 characters!");
        }
        else if(user_number.length()!= 10){
            JOptionPane.showMessageDialog(null, "Check the conatct number again");
        }else if(! user_email.contains("@")){
            JOptionPane.showMessageDialog(null, "Enter a valid E-mail address.");    
        }
        else{
        try {
            String sql = "INSERT INTO user(user_name, user_password, mobile_number, email)VALUES (?,?,?,?)";
            PreparedStatement add = conn.prepareStatement(sql);
            add.setString(1, user_name);
            add.setString(2, user_password);
            add.setString(3, user_number);
            add.setString(4, user_email);
            int rowsAffected = add.executeUpdate();
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "User Registration Successful!");
                        Login admin = new Login();
                        admin.setVisible(true);
                        this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "User Registration Failed!\n Try Again!");}
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Error occurs at User registration : "+e);
        }
        }
    }//GEN-LAST:event_register_bttnActionPerformed

    private void back_log_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_log_bttnActionPerformed
        // TODO add your handling code here:
        Login admin = new Login();
        admin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_log_bttnActionPerformed

    private void clear_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_bttnActionPerformed
        // TODO add your handling code here:
        uName.setText("");
        eMail.setText("");
        contact.setText("");
        password.setText("");
    }//GEN-LAST:event_clear_bttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new UserReg().setVisible(true);
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null,"Error occurs at User UserReg Main : "+e);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_log_bttn;
    private javax.swing.JButton clear_bttn;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField eMail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton register_bttn;
    private javax.swing.JTextField uName;
    // End of variables declaration//GEN-END:variables
private void Reconnect() throws SQLException{
    if (this.conn == null || this.conn.isClosed()) {
        try {
            // Re-establish the connection
            String jdbcUrl = "jdbc:mysql://localhost:3306/event_reservation";
            String username = "root";
            String db_password = null;
            this.conn = DriverManager.getConnection(jdbcUrl, username, db_password);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Error occurs When reconnecting Database :"+e);
        }
}
}
}
