
package GUI;

import java.sql.PreparedStatement;
import java.sql.Connection;
import CODE.DbConnect;

public class UserProfile extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    
    public UserProfile() {
        initComponents();
        conn = (Connection) DbConnect.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        venue = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        about = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ticket_detail_table = new javax.swing.JTable();
        category_table = new javax.swing.JComboBox<>();
        selecting_seats = new javax.swing.JTextField();
        check_bttn = new javax.swing.JButton();
        book_bttn = new javax.swing.JButton();
        eventCombo = new javax.swing.JComboBox<>();
        search_bttn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        editProfile_bttn = new javax.swing.JMenuItem();
        reservation_bttn = new javax.swing.JMenuItem();
        logout_bttn = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Event  Reservation System");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 102, 102)));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 540, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 700, 110));

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel2.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Find event :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 120, -1));

        jLabel3.setBackground(new java.awt.Color(0, 102, 102));
        jLabel3.setFont(new java.awt.Font("Cinzel Black", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Check Availability Here !");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, 40));

        jLabel7.setBackground(new java.awt.Color(0, 102, 102));
        jLabel7.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Venue :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 102, 102));
        jLabel4.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 60, -1));

        jLabel5.setBackground(new java.awt.Color(0, 102, 102));
        jLabel5.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("About:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 80, -1));

        jLabel8.setBackground(new java.awt.Color(0, 102, 102));
        jLabel8.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ticket Prices : ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 140, -1));

        jLabel6.setBackground(new java.awt.Color(0, 102, 102));
        jLabel6.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Check Seat Availability :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 163, 710, 10));
        jPanel1.add(venue, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 330, -1));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 330, -1));

        about.setColumns(20);
        about.setRows(5);
        about.setToolTipText("Give a description  about the event.");
        jScrollPane1.setViewportView(about);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 330, 80));

        ticket_detail_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Category", " Ticket Price", "No. of seats"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ticket_detail_table);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 330, 70));

        jPanel1.add(category_table, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, 80, -1));
        jPanel1.add(selecting_seats, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, 80, -1));

        check_bttn.setBackground(new java.awt.Color(204, 204, 204));
        check_bttn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        check_bttn.setText("Check");
        check_bttn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        check_bttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(check_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, 60, -1));

        book_bttn.setBackground(new java.awt.Color(204, 204, 204));
        book_bttn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        book_bttn.setText("Book Now");
        book_bttn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        book_bttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        book_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_bttnActionPerformed(evt);
            }
        });
        jPanel1.add(book_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, 80, -1));

        jPanel1.add(eventCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 340, -1));

        search_bttn.setBackground(new java.awt.Color(204, 204, 204));
        search_bttn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        search_bttn.setText("Search");
        search_bttn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        search_bttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(search_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 60, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 710, 600));

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));

        jMenu1.setText("My profile");

        editProfile_bttn.setText("Edit  profile info");
        editProfile_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfile_bttnActionPerformed(evt);
            }
        });
        jMenu1.add(editProfile_bttn);

        reservation_bttn.setText("Reservations");
        reservation_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservation_bttnActionPerformed(evt);
            }
        });
        jMenu1.add(reservation_bttn);

        logout_bttn.setText("Logout");
        logout_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_bttnActionPerformed(evt);
            }
        });
        jMenu1.add(logout_bttn);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void book_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_bttnActionPerformed
        // TODO add your handling code here:
        Reserve objBooking = new Reserve();
        objBooking.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_book_bttnActionPerformed

    private void editProfile_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfile_bttnActionPerformed
        // TODO add your handling code here:
        UpdateUserInfo user = new UpdateUserInfo();
        user.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_editProfile_bttnActionPerformed

    private void reservation_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservation_bttnActionPerformed
        // TODO add your handling code here:
        UserReservation userRes = new UserReservation();
        userRes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reservation_bttnActionPerformed

    private void logout_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_bttnActionPerformed
        // TODO add your handling code here:
        Login userLogout = new Login();
        userLogout.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logout_bttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea about;
    private javax.swing.JButton book_bttn;
    private javax.swing.JComboBox<String> category_table;
    private javax.swing.JButton check_bttn;
    private javax.swing.JTextField date;
    private javax.swing.JMenuItem editProfile_bttn;
    private javax.swing.JComboBox<String> eventCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem logout_bttn;
    private javax.swing.JMenuItem reservation_bttn;
    private javax.swing.JButton search_bttn;
    private javax.swing.JTextField selecting_seats;
    private javax.swing.JTable ticket_detail_table;
    private javax.swing.JTextField venue;
    // End of variables declaration//GEN-END:variables
}
