/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import CODE.DbConnect;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class UserReservation extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    public int userID = 0;
    
    /**
     * Creates new form UserReservation
     */
    public UserReservation() {
        initComponents();
        conn= DbConnect.connect();
        try {
            showTable();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        res_ticket_reservation = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        select_ticket = new javax.swing.JComboBox<>();
        cancle_bttn = new javax.swing.JButton();
        back_user_bttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("User Profile");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 240, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 100));

        jLabel2.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Canceling Reservations:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 282, 240, 30));

        res_ticket_reservation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Event", "Reserved category", "Reserved Seats"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(res_ticket_reservation);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, 90));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 570, -1));

        jLabel3.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Reserved Ticket Details :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 240, 30));

        select_ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_ticketActionPerformed(evt);
            }
        });
        jPanel1.add(select_ticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 450, -1));

        cancle_bttn.setBackground(new java.awt.Color(204, 204, 204));
        cancle_bttn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        cancle_bttn.setText("Cancle");
        cancle_bttn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancle_bttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancle_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancle_bttnActionPerformed(evt);
            }
        });
        jPanel1.add(cancle_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 50, -1));

        back_user_bttn.setBackground(new java.awt.Color(204, 204, 204));
        back_user_bttn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        back_user_bttn.setText("Back");
        back_user_bttn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back_user_bttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_user_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_user_bttnActionPerformed(evt);
            }
        });
        jPanel1.add(back_user_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 50, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancle_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancle_bttnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Do you want to remove the reservation?");
        try{String sql2 = "DELETE FROM  booking  where user_ID = ?";
        PreparedStatement add = conn.prepareStatement(sql2);
        add.setInt(1, userID);
        add.executeQuery();
        JOptionPane.showMessageDialog(null, "Resrvation successfully cancled!");
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cancle_bttnActionPerformed

    private void back_user_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_user_bttnActionPerformed
        try {
            // TODO add your handling code here
            UserProfile user = new UserProfile();
            user.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    
        
    }//GEN-LAST:event_back_user_bttnActionPerformed

    private void select_ticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_ticketActionPerformed
        // TODO add your handling code here:
        try{
       
        String sql1 = "SELECT event_table.event_Name FROM booking JOIN event_table ON booking.event_ID = event_table.event_ID where user_ID=?";
        PreparedStatement add = conn.prepareStatement(sql1);
        add.setInt(1, userID);
        rs = add.executeQuery();
        
        while(rs.next()){
            String name = rs.getString("event_name");
            select_ticket.addItem(name);
        }
        conn.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        
        }
    }//GEN-LAST:event_select_ticketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UserReservation().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_user_bttn;
    private javax.swing.JButton cancle_bttn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable res_ticket_reservation;
    private javax.swing.JComboBox<String> select_ticket;
    // End of variables declaration//GEN-END:variables

    private void showTable() throws SQLException {
        try {
            try {
            if (this.conn == null || this.conn.isClosed()) {
                // Re-establish the connection
                String jdbcUrl = "jdbc:mysql://localhost:3306/event_reservation";
                String username = "root";
                String password = "";
                this.conn = DriverManager.getConnection(jdbcUrl, username, password);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,e);
        }
            String sql2 = "SELECT seats.seat_category,seats.NoOf_seats,event_table.event_Name FROM seats JOIN event_table ON seats.event_ID = event_table.event_ID";
            pst = conn.prepareStatement(sql2);
            rs = pst.executeQuery();
            while(rs.next()){
                String seat_type = rs.getString("seat_category");
                String number_of = String.valueOf(rs.getInt("NoOf_seats"));
                String eventName = rs.getString("event_Name");
                
                String tbData[]= {seat_type,number_of ,eventName};
                DefaultTableModel tblModel = (DefaultTableModel)res_ticket_reservation.getModel();
                
                tblModel.addRow(tbData);
            }
             }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null,e);
            }
    }

}
